init_state_values:
- - 0.45
  - 1.4
  - 0.01
  - -0.13
  - 0.7
other_params:
- float_params:
    variances:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  int_params: {}
seeds:
- 4673
state_history_depths:
- 2
state_widths:
- 5
timesteps_history_depth: 2
