simulator:
  iterations:
  - "firstWienerProcess"
  - "secondWienerProcess"
  output_condition: "&simulator.EveryStepOutputCondition{}"
  output_function: "&simulator.StdoutOutputFunction{}"
  termination_condition: "&simulator.NumberOfStepsTerminationCondition{MaxNumberOfSteps: 100}"
  timestep_function: "&simulator.ConstantTimestepFunction{Stepsize: 1.0}"
agents:
- actor: "&interactions.DoNothingActor{}"
  generator: "&interactions.DoNothingActionGenerator{}"
  observation: "&interactions.GaussianNoiseStateObservation{}"
- actor: "&interactions.DoNothingActor{}"
  generator: "&interactions.DoNothingActionGenerator{}"
  observation: "&interactions.GaussianNoiseStateObservation{}"
extra_vars_by_package:
- github.com/umbralcalc/stochadex/pkg/phenomena:
  - firstWienerProcess: "&phenomena.WienerProcessIteration{}"
  - secondWienerProcess: "&phenomena.WienerProcessIteration{}"