other_params:
- float_params:
    variances: [1.0, 1.0, 1.0, 1.0, 1.0]
    observation_noise_variances: [0.5, 0.5, 0.5, 0.5, 0.5]
    # init_action_values: []
  int_params: {}
- float_params:
    variances: [1.0, 1.0, 1.0]
    observation_noise_variances: [0.5, 0.5, 0.5]
    # init_action_values: []
  int_params: {}
init_state_values:
- [0.45, 1.4, 0.01, -0.13, 0.7]
- [0.67, -0.01, 0.1]
init_time_value: 0.0
seeds: [4673, 2783]
state_widths: [5, 3]
state_history_depths: [2, 2]
timesteps_history_depth: 2