/*
cgo stubs for package api.
File is generated by gopy. Do not edit.
gopy build -output=python -vm=python3 github.com/worldsoop/worldsoop/pkg/api
*/

package main

/*

#cgo CFLAGS: -I/usr/include/python3.10 -Wno-error -Wno-implicit-function-declaration -Wno-int-conversion
#cgo LDFLAGS: -L/usr/lib/x86_64-linux-gnu -lpython3.10 -lcrypt -ldl  -lm -lm

// #define Py_LIMITED_API // need full API for PyRun*
#include <Python.h>
typedef uint8_t bool;
// static inline is trick for avoiding need for extra .c file
// the following are used for build value -- switch on reflect.Kind
// or the types equivalent
static inline PyObject* gopy_build_bool(uint8_t val) {
	return Py_BuildValue("b", val);
}
static inline PyObject* gopy_build_int64(int64_t val) {
	return Py_BuildValue("k", val);
}
static inline PyObject* gopy_build_uint64(uint64_t val) {
	return Py_BuildValue("K", val);
}
static inline PyObject* gopy_build_float64(double val) {
	return Py_BuildValue("d", val);
}
static inline PyObject* gopy_build_string(const char* val) {
	return Py_BuildValue("s", val);
}
static inline void gopy_decref(PyObject* obj) { // macro
	Py_XDECREF(obj);
}
static inline void gopy_incref(PyObject* obj) { // macro
	Py_XINCREF(obj);
}
static inline int gopy_method_check(PyObject* obj) { // macro
	return PyMethod_Check(obj);
}
static inline void gopy_err_handle() {
	if(PyErr_Occurred() != NULL) {
		PyErr_Print();
	}
}

*/
import "C"
import (
	"errors"
	"reflect"

	"github.com/go-python/gopy/gopyh" // handler

	"sync"

	"github.com/umbralcalc/stochadex/pkg/interactions"
	"github.com/umbralcalc/stochadex/pkg/simulator"
	"github.com/worldsoop/worldsoop/pkg/api"
)

// main doesn't do anything in lib / pkg mode, but is essential for exe mode
func main() {

}

// initialization functions -- can be called from python after library is loaded
// GoPyInitRunFile runs a separate python file -- call in GoPyInit if it
// steals the main thread e.g., for GUI event loop, as in GoGi startup.

//export GoPyInit
func GoPyInit() {

}

// type for the handle -- int64 for speed (can switch to string)
type GoHandle int64
type CGoHandle C.longlong

// DecRef decrements the reference count for the specified handle
// and deletes it it goes to zero.
//export DecRef
func DecRef(handle CGoHandle) {
	gopyh.DecRef(gopyh.CGoHandle(handle))
}

// IncRef increments the reference count for the specified handle.
//export IncRef
func IncRef(handle CGoHandle) {
	gopyh.IncRef(gopyh.CGoHandle(handle))
}

// NumHandles returns the number of handles currently in use.
//export NumHandles
func NumHandles() int {
	return gopyh.NumHandles()
}

// boolGoToPy converts a Go bool to python-compatible C.char
func boolGoToPy(b bool) C.char {
	if b {
		return 1
	}
	return 0
}

// boolPyToGo converts a python-compatible C.Char to Go bool
func boolPyToGo(b C.char) bool {
	if b != 0 {
		return true
	}
	return false
}

func complex64GoToPy(c complex64) *C.PyObject {
	return C.PyComplex_FromDoubles(C.double(real(c)), C.double(imag(c)))
}

func complex64PyToGo(o *C.PyObject) complex64 {
	v := C.PyComplex_AsCComplex(o)
	return complex(float32(v.real), float32(v.imag))
}

func complex128GoToPy(c complex128) *C.PyObject {
	return C.PyComplex_FromDoubles(C.double(real(c)), C.double(imag(c)))
}

func complex128PyToGo(o *C.PyObject) complex128 {
	v := C.PyComplex_AsCComplex(o)
	return complex(float64(v.real), float64(v.imag))
}

// errorGoToPy converts a Go error to python-compatible C.CString
func errorGoToPy(e error) *C.char {
	if e != nil {
		return C.CString(e.Error())
	}
	return C.CString("")
}

// --- generated code for package: api below: ---

// ---- External Types Outside of Targeted Packages ---

// Converters for pointer handles for type: *interactions.AgentConfig
func ptrFromHandle_Ptr_interactions_AgentConfig(h CGoHandle) *interactions.AgentConfig {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "*interactions.AgentConfig")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(interactions.AgentConfig{})).(*interactions.AgentConfig)
}
func handleFromPtr_Ptr_interactions_AgentConfig(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("*interactions.AgentConfig", p))
}

// Converters for pointer handles for type: *simulator.LoadImplementationsConfig
func ptrFromHandle_Ptr_simulator_LoadImplementationsConfig(h CGoHandle) *simulator.LoadImplementationsConfig {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "*simulator.LoadImplementationsConfig")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(simulator.LoadImplementationsConfig{})).(*simulator.LoadImplementationsConfig)
}
func handleFromPtr_Ptr_simulator_LoadImplementationsConfig(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("*simulator.LoadImplementationsConfig", p))
}

// Converters for pointer handles for type: *simulator.LoadSettingsConfig
func ptrFromHandle_Ptr_simulator_LoadSettingsConfig(h CGoHandle) *simulator.LoadSettingsConfig {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "*simulator.LoadSettingsConfig")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(simulator.LoadSettingsConfig{})).(*simulator.LoadSettingsConfig)
}
func handleFromPtr_Ptr_simulator_LoadSettingsConfig(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("*simulator.LoadSettingsConfig", p))
}

// Converters for pointer handles for type: *simulator.OtherParams
func ptrFromHandle_Ptr_simulator_OtherParams(h CGoHandle) *simulator.OtherParams {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "*simulator.OtherParams")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(simulator.OtherParams{})).(*simulator.OtherParams)
}
func handleFromPtr_Ptr_simulator_OtherParams(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("*simulator.OtherParams", p))
}

// Converters for pointer handles for type: *sync.WaitGroup
func ptrFromHandle_Ptr_sync_WaitGroup(h CGoHandle) *sync.WaitGroup {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "*sync.WaitGroup")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(sync.WaitGroup{})).(*sync.WaitGroup)
}
func handleFromPtr_Ptr_sync_WaitGroup(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("*sync.WaitGroup", p))
}

// Converters for pointer handles for type: interactions.ActionGenerator
func ptrFromHandle_interactions_ActionGenerator(h CGoHandle) interactions.ActionGenerator {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "interactions.ActionGenerator")
	if p == nil {
		return nil
	}
	return p.(interactions.ActionGenerator)
}
func handleFromPtr_interactions_ActionGenerator(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("interactions.ActionGenerator", p))
}

// Converters for pointer handles for type: interactions.Actor
func ptrFromHandle_interactions_Actor(h CGoHandle) interactions.Actor {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "interactions.Actor")
	if p == nil {
		return nil
	}
	return p.(interactions.Actor)
}
func handleFromPtr_interactions_Actor(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("interactions.Actor", p))
}

// Converters for non-pointer handles for type: interactions.AgentConfig
func ptrFromHandle_interactions_AgentConfig(h CGoHandle) *interactions.AgentConfig {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "interactions.AgentConfig")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(interactions.AgentConfig{})).(*interactions.AgentConfig)
}
func handleFromPtr_interactions_AgentConfig(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("interactions.AgentConfig", p))
}

// Converters for pointer handles for type: interactions.StateObservation
func ptrFromHandle_interactions_StateObservation(h CGoHandle) interactions.StateObservation {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "interactions.StateObservation")
	if p == nil {
		return nil
	}
	return p.(interactions.StateObservation)
}
func handleFromPtr_interactions_StateObservation(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("interactions.StateObservation", p))
}

// Converters for pointer handles for type: simulator.Iteration
func ptrFromHandle_simulator_Iteration(h CGoHandle) simulator.Iteration {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.Iteration")
	if p == nil {
		return nil
	}
	return p.(simulator.Iteration)
}
func handleFromPtr_simulator_Iteration(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.Iteration", p))
}

// Converters for non-pointer handles for type: simulator.LoadImplementationsConfig
func ptrFromHandle_simulator_LoadImplementationsConfig(h CGoHandle) *simulator.LoadImplementationsConfig {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.LoadImplementationsConfig")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(simulator.LoadImplementationsConfig{})).(*simulator.LoadImplementationsConfig)
}
func handleFromPtr_simulator_LoadImplementationsConfig(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.LoadImplementationsConfig", p))
}

// Converters for non-pointer handles for type: simulator.LoadSettingsConfig
func ptrFromHandle_simulator_LoadSettingsConfig(h CGoHandle) *simulator.LoadSettingsConfig {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.LoadSettingsConfig")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(simulator.LoadSettingsConfig{})).(*simulator.LoadSettingsConfig)
}
func handleFromPtr_simulator_LoadSettingsConfig(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.LoadSettingsConfig", p))
}

// Converters for non-pointer handles for type: simulator.OtherParams
func ptrFromHandle_simulator_OtherParams(h CGoHandle) *simulator.OtherParams {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.OtherParams")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(simulator.OtherParams{})).(*simulator.OtherParams)
}
func handleFromPtr_simulator_OtherParams(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.OtherParams", p))
}

// Converters for pointer handles for type: simulator.OutputCondition
func ptrFromHandle_simulator_OutputCondition(h CGoHandle) simulator.OutputCondition {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.OutputCondition")
	if p == nil {
		return nil
	}
	return p.(simulator.OutputCondition)
}
func handleFromPtr_simulator_OutputCondition(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.OutputCondition", p))
}

// Converters for pointer handles for type: simulator.OutputFunction
func ptrFromHandle_simulator_OutputFunction(h CGoHandle) simulator.OutputFunction {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.OutputFunction")
	if p == nil {
		return nil
	}
	return p.(simulator.OutputFunction)
}
func handleFromPtr_simulator_OutputFunction(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.OutputFunction", p))
}

// Converters for pointer handles for type: simulator.TerminationCondition
func ptrFromHandle_simulator_TerminationCondition(h CGoHandle) simulator.TerminationCondition {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.TerminationCondition")
	if p == nil {
		return nil
	}
	return p.(simulator.TerminationCondition)
}
func handleFromPtr_simulator_TerminationCondition(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.TerminationCondition", p))
}

// Converters for pointer handles for type: simulator.TimestepFunction
func ptrFromHandle_simulator_TimestepFunction(h CGoHandle) simulator.TimestepFunction {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "simulator.TimestepFunction")
	if p == nil {
		return nil
	}
	return p.(simulator.TimestepFunction)
}
func handleFromPtr_simulator_TimestepFunction(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("simulator.TimestepFunction", p))
}

// Converters for non-pointer handles for type: sync.WaitGroup
func ptrFromHandle_sync_WaitGroup(h CGoHandle) *sync.WaitGroup {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "sync.WaitGroup")
	if p == nil {
		return nil
	}
	return gopyh.Embed(p, reflect.TypeOf(sync.WaitGroup{})).(*sync.WaitGroup)
}
func handleFromPtr_sync_WaitGroup(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("sync.WaitGroup", p))
}

// ---- Package: go ---

// ---- Types ---

// Converters for implicit pointer handles for type: []bool
func ptrFromHandle_Slice_bool(h CGoHandle) *[]bool {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]bool")
	if p == nil {
		return nil
	}
	return p.(*[]bool)
}
func deptrFromHandle_Slice_bool(h CGoHandle) []bool {
	p := ptrFromHandle_Slice_bool(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_bool(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]bool", p))
}

// --- wrapping slice: []bool ---
//export Slice_bool_CTor
func Slice_bool_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_bool(&[]bool{}))
}

//export Slice_bool_len
func Slice_bool_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_bool(handle))
}

//export Slice_bool_elem
func Slice_bool_elem(handle CGoHandle, _idx int) C.char {
	s := deptrFromHandle_Slice_bool(handle)
	return boolGoToPy(s[_idx])
}

//export Slice_bool_subslice
func Slice_bool_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_bool(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_bool(&ss))
}

//export Slice_bool_set
func Slice_bool_set(handle CGoHandle, _idx int, _vl C.char) {
	s := deptrFromHandle_Slice_bool(handle)
	s[_idx] = boolPyToGo(_vl)
}

//export Slice_bool_append
func Slice_bool_append(handle CGoHandle, _vl C.char) {
	s := ptrFromHandle_Slice_bool(handle)
	*s = append(*s, boolPyToGo(_vl))
}

// Converters for implicit pointer handles for type: []byte
func ptrFromHandle_Slice_byte(h CGoHandle) *[]byte {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]byte")
	if p == nil {
		return nil
	}
	return p.(*[]byte)
}
func deptrFromHandle_Slice_byte(h CGoHandle) []byte {
	p := ptrFromHandle_Slice_byte(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_byte(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]byte", p))
}

// --- wrapping slice: []byte ---
//export Slice_byte_CTor
func Slice_byte_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_byte(&[]byte{}))
}

//export Slice_byte_len
func Slice_byte_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_byte(handle))
}

//export Slice_byte_elem
func Slice_byte_elem(handle CGoHandle, _idx int) C.char {
	s := deptrFromHandle_Slice_byte(handle)
	return C.char(s[_idx])
}

//export Slice_byte_subslice
func Slice_byte_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_byte(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_byte(&ss))
}

//export Slice_byte_set
func Slice_byte_set(handle CGoHandle, _idx int, _vl C.char) {
	s := deptrFromHandle_Slice_byte(handle)
	s[_idx] = byte(_vl)
}

//export Slice_byte_append
func Slice_byte_append(handle CGoHandle, _vl C.char) {
	s := ptrFromHandle_Slice_byte(handle)
	*s = append(*s, byte(_vl))
}

// Converters for implicit pointer handles for type: []error
func ptrFromHandle_Slice_error(h CGoHandle) *[]error {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]error")
	if p == nil {
		return nil
	}
	return p.(*[]error)
}
func deptrFromHandle_Slice_error(h CGoHandle) []error {
	p := ptrFromHandle_Slice_error(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_error(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]error", p))
}

// --- wrapping slice: []error ---
//export Slice_error_CTor
func Slice_error_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_error(&[]error{}))
}

//export Slice_error_len
func Slice_error_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_error(handle))
}

//export Slice_error_elem
func Slice_error_elem(handle CGoHandle, _idx int) *C.char {
	s := deptrFromHandle_Slice_error(handle)
	return errorGoToPy(s[_idx])
}

//export Slice_error_subslice
func Slice_error_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_error(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_error(&ss))
}

//export Slice_error_set
func Slice_error_set(handle CGoHandle, _idx int, _vl *C.char) {
	s := deptrFromHandle_Slice_error(handle)
	s[_idx] = errors.New(C.GoString(_vl))
}

//export Slice_error_append
func Slice_error_append(handle CGoHandle, _vl *C.char) {
	s := ptrFromHandle_Slice_error(handle)
	*s = append(*s, errors.New(C.GoString(_vl)))
}

// Converters for implicit pointer handles for type: []float32
func ptrFromHandle_Slice_float32(h CGoHandle) *[]float32 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]float32")
	if p == nil {
		return nil
	}
	return p.(*[]float32)
}
func deptrFromHandle_Slice_float32(h CGoHandle) []float32 {
	p := ptrFromHandle_Slice_float32(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_float32(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]float32", p))
}

// --- wrapping slice: []float32 ---
//export Slice_float32_CTor
func Slice_float32_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_float32(&[]float32{}))
}

//export Slice_float32_len
func Slice_float32_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_float32(handle))
}

//export Slice_float32_elem
func Slice_float32_elem(handle CGoHandle, _idx int) C.float {
	s := deptrFromHandle_Slice_float32(handle)
	return C.float(s[_idx])
}

//export Slice_float32_subslice
func Slice_float32_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_float32(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_float32(&ss))
}

//export Slice_float32_set
func Slice_float32_set(handle CGoHandle, _idx int, _vl C.float) {
	s := deptrFromHandle_Slice_float32(handle)
	s[_idx] = float32(_vl)
}

//export Slice_float32_append
func Slice_float32_append(handle CGoHandle, _vl C.float) {
	s := ptrFromHandle_Slice_float32(handle)
	*s = append(*s, float32(_vl))
}

// Converters for implicit pointer handles for type: []float64
func ptrFromHandle_Slice_float64(h CGoHandle) *[]float64 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]float64")
	if p == nil {
		return nil
	}
	return p.(*[]float64)
}
func deptrFromHandle_Slice_float64(h CGoHandle) []float64 {
	p := ptrFromHandle_Slice_float64(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_float64(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]float64", p))
}

// --- wrapping slice: []float64 ---
//export Slice_float64_CTor
func Slice_float64_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_float64(&[]float64{}))
}

//export Slice_float64_len
func Slice_float64_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_float64(handle))
}

//export Slice_float64_elem
func Slice_float64_elem(handle CGoHandle, _idx int) C.double {
	s := deptrFromHandle_Slice_float64(handle)
	return C.double(s[_idx])
}

//export Slice_float64_subslice
func Slice_float64_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_float64(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_float64(&ss))
}

//export Slice_float64_set
func Slice_float64_set(handle CGoHandle, _idx int, _vl C.double) {
	s := deptrFromHandle_Slice_float64(handle)
	s[_idx] = float64(_vl)
}

//export Slice_float64_append
func Slice_float64_append(handle CGoHandle, _vl C.double) {
	s := ptrFromHandle_Slice_float64(handle)
	*s = append(*s, float64(_vl))
}

// Converters for implicit pointer handles for type: []int
func ptrFromHandle_Slice_int(h CGoHandle) *[]int {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]int")
	if p == nil {
		return nil
	}
	return p.(*[]int)
}
func deptrFromHandle_Slice_int(h CGoHandle) []int {
	p := ptrFromHandle_Slice_int(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_int(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]int", p))
}

// --- wrapping slice: []int ---
//export Slice_int_CTor
func Slice_int_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_int(&[]int{}))
}

//export Slice_int_len
func Slice_int_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_int(handle))
}

//export Slice_int_elem
func Slice_int_elem(handle CGoHandle, _idx int) C.longlong {
	s := deptrFromHandle_Slice_int(handle)
	return C.longlong(s[_idx])
}

//export Slice_int_subslice
func Slice_int_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_int(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_int(&ss))
}

//export Slice_int_set
func Slice_int_set(handle CGoHandle, _idx int, _vl C.longlong) {
	s := deptrFromHandle_Slice_int(handle)
	s[_idx] = int(_vl)
}

//export Slice_int_append
func Slice_int_append(handle CGoHandle, _vl C.longlong) {
	s := ptrFromHandle_Slice_int(handle)
	*s = append(*s, int(_vl))
}

// Converters for implicit pointer handles for type: []int16
func ptrFromHandle_Slice_int16(h CGoHandle) *[]int16 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]int16")
	if p == nil {
		return nil
	}
	return p.(*[]int16)
}
func deptrFromHandle_Slice_int16(h CGoHandle) []int16 {
	p := ptrFromHandle_Slice_int16(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_int16(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]int16", p))
}

// --- wrapping slice: []int16 ---
//export Slice_int16_CTor
func Slice_int16_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_int16(&[]int16{}))
}

//export Slice_int16_len
func Slice_int16_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_int16(handle))
}

//export Slice_int16_elem
func Slice_int16_elem(handle CGoHandle, _idx int) C.short {
	s := deptrFromHandle_Slice_int16(handle)
	return C.short(s[_idx])
}

//export Slice_int16_subslice
func Slice_int16_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_int16(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_int16(&ss))
}

//export Slice_int16_set
func Slice_int16_set(handle CGoHandle, _idx int, _vl C.short) {
	s := deptrFromHandle_Slice_int16(handle)
	s[_idx] = int16(_vl)
}

//export Slice_int16_append
func Slice_int16_append(handle CGoHandle, _vl C.short) {
	s := ptrFromHandle_Slice_int16(handle)
	*s = append(*s, int16(_vl))
}

// Converters for implicit pointer handles for type: []int32
func ptrFromHandle_Slice_int32(h CGoHandle) *[]int32 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]int32")
	if p == nil {
		return nil
	}
	return p.(*[]int32)
}
func deptrFromHandle_Slice_int32(h CGoHandle) []int32 {
	p := ptrFromHandle_Slice_int32(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_int32(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]int32", p))
}

// --- wrapping slice: []int32 ---
//export Slice_int32_CTor
func Slice_int32_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_int32(&[]int32{}))
}

//export Slice_int32_len
func Slice_int32_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_int32(handle))
}

//export Slice_int32_elem
func Slice_int32_elem(handle CGoHandle, _idx int) C.long {
	s := deptrFromHandle_Slice_int32(handle)
	return C.long(s[_idx])
}

//export Slice_int32_subslice
func Slice_int32_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_int32(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_int32(&ss))
}

//export Slice_int32_set
func Slice_int32_set(handle CGoHandle, _idx int, _vl C.long) {
	s := deptrFromHandle_Slice_int32(handle)
	s[_idx] = int32(_vl)
}

//export Slice_int32_append
func Slice_int32_append(handle CGoHandle, _vl C.long) {
	s := ptrFromHandle_Slice_int32(handle)
	*s = append(*s, int32(_vl))
}

// Converters for implicit pointer handles for type: []int64
func ptrFromHandle_Slice_int64(h CGoHandle) *[]int64 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]int64")
	if p == nil {
		return nil
	}
	return p.(*[]int64)
}
func deptrFromHandle_Slice_int64(h CGoHandle) []int64 {
	p := ptrFromHandle_Slice_int64(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_int64(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]int64", p))
}

// --- wrapping slice: []int64 ---
//export Slice_int64_CTor
func Slice_int64_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_int64(&[]int64{}))
}

//export Slice_int64_len
func Slice_int64_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_int64(handle))
}

//export Slice_int64_elem
func Slice_int64_elem(handle CGoHandle, _idx int) C.longlong {
	s := deptrFromHandle_Slice_int64(handle)
	return C.longlong(s[_idx])
}

//export Slice_int64_subslice
func Slice_int64_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_int64(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_int64(&ss))
}

//export Slice_int64_set
func Slice_int64_set(handle CGoHandle, _idx int, _vl C.longlong) {
	s := deptrFromHandle_Slice_int64(handle)
	s[_idx] = int64(_vl)
}

//export Slice_int64_append
func Slice_int64_append(handle CGoHandle, _vl C.longlong) {
	s := ptrFromHandle_Slice_int64(handle)
	*s = append(*s, int64(_vl))
}

// Converters for implicit pointer handles for type: []int8
func ptrFromHandle_Slice_int8(h CGoHandle) *[]int8 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]int8")
	if p == nil {
		return nil
	}
	return p.(*[]int8)
}
func deptrFromHandle_Slice_int8(h CGoHandle) []int8 {
	p := ptrFromHandle_Slice_int8(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_int8(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]int8", p))
}

// --- wrapping slice: []int8 ---
//export Slice_int8_CTor
func Slice_int8_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_int8(&[]int8{}))
}

//export Slice_int8_len
func Slice_int8_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_int8(handle))
}

//export Slice_int8_elem
func Slice_int8_elem(handle CGoHandle, _idx int) C.char {
	s := deptrFromHandle_Slice_int8(handle)
	return C.char(s[_idx])
}

//export Slice_int8_subslice
func Slice_int8_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_int8(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_int8(&ss))
}

//export Slice_int8_set
func Slice_int8_set(handle CGoHandle, _idx int, _vl C.char) {
	s := deptrFromHandle_Slice_int8(handle)
	s[_idx] = int8(_vl)
}

//export Slice_int8_append
func Slice_int8_append(handle CGoHandle, _vl C.char) {
	s := ptrFromHandle_Slice_int8(handle)
	*s = append(*s, int8(_vl))
}

// Converters for implicit pointer handles for type: []rune
func ptrFromHandle_Slice_rune(h CGoHandle) *[]rune {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]rune")
	if p == nil {
		return nil
	}
	return p.(*[]rune)
}
func deptrFromHandle_Slice_rune(h CGoHandle) []rune {
	p := ptrFromHandle_Slice_rune(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_rune(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]rune", p))
}

// --- wrapping slice: []rune ---
//export Slice_rune_CTor
func Slice_rune_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_rune(&[]rune{}))
}

//export Slice_rune_len
func Slice_rune_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_rune(handle))
}

//export Slice_rune_elem
func Slice_rune_elem(handle CGoHandle, _idx int) C.long {
	s := deptrFromHandle_Slice_rune(handle)
	return C.long(s[_idx])
}

//export Slice_rune_subslice
func Slice_rune_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_rune(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_rune(&ss))
}

//export Slice_rune_set
func Slice_rune_set(handle CGoHandle, _idx int, _vl C.long) {
	s := deptrFromHandle_Slice_rune(handle)
	s[_idx] = rune(_vl)
}

//export Slice_rune_append
func Slice_rune_append(handle CGoHandle, _vl C.long) {
	s := ptrFromHandle_Slice_rune(handle)
	*s = append(*s, rune(_vl))
}

// Converters for implicit pointer handles for type: []string
func ptrFromHandle_Slice_string(h CGoHandle) *[]string {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]string")
	if p == nil {
		return nil
	}
	return p.(*[]string)
}
func deptrFromHandle_Slice_string(h CGoHandle) []string {
	p := ptrFromHandle_Slice_string(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_string(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]string", p))
}

// --- wrapping slice: []string ---
//export Slice_string_CTor
func Slice_string_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_string(&[]string{}))
}

//export Slice_string_len
func Slice_string_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_string(handle))
}

//export Slice_string_elem
func Slice_string_elem(handle CGoHandle, _idx int) *C.char {
	s := deptrFromHandle_Slice_string(handle)
	return C.CString(s[_idx])
}

//export Slice_string_subslice
func Slice_string_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_string(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_string(&ss))
}

//export Slice_string_set
func Slice_string_set(handle CGoHandle, _idx int, _vl *C.char) {
	s := deptrFromHandle_Slice_string(handle)
	s[_idx] = C.GoString(_vl)
}

//export Slice_string_append
func Slice_string_append(handle CGoHandle, _vl *C.char) {
	s := ptrFromHandle_Slice_string(handle)
	*s = append(*s, C.GoString(_vl))
}

// Converters for implicit pointer handles for type: []uint
func ptrFromHandle_Slice_uint(h CGoHandle) *[]uint {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]uint")
	if p == nil {
		return nil
	}
	return p.(*[]uint)
}
func deptrFromHandle_Slice_uint(h CGoHandle) []uint {
	p := ptrFromHandle_Slice_uint(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_uint(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]uint", p))
}

// --- wrapping slice: []uint ---
//export Slice_uint_CTor
func Slice_uint_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_uint(&[]uint{}))
}

//export Slice_uint_len
func Slice_uint_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_uint(handle))
}

//export Slice_uint_elem
func Slice_uint_elem(handle CGoHandle, _idx int) C.ulonglong {
	s := deptrFromHandle_Slice_uint(handle)
	return C.ulonglong(s[_idx])
}

//export Slice_uint_subslice
func Slice_uint_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_uint(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_uint(&ss))
}

//export Slice_uint_set
func Slice_uint_set(handle CGoHandle, _idx int, _vl C.ulonglong) {
	s := deptrFromHandle_Slice_uint(handle)
	s[_idx] = uint(_vl)
}

//export Slice_uint_append
func Slice_uint_append(handle CGoHandle, _vl C.ulonglong) {
	s := ptrFromHandle_Slice_uint(handle)
	*s = append(*s, uint(_vl))
}

// Converters for implicit pointer handles for type: []uint16
func ptrFromHandle_Slice_uint16(h CGoHandle) *[]uint16 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]uint16")
	if p == nil {
		return nil
	}
	return p.(*[]uint16)
}
func deptrFromHandle_Slice_uint16(h CGoHandle) []uint16 {
	p := ptrFromHandle_Slice_uint16(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_uint16(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]uint16", p))
}

// --- wrapping slice: []uint16 ---
//export Slice_uint16_CTor
func Slice_uint16_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_uint16(&[]uint16{}))
}

//export Slice_uint16_len
func Slice_uint16_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_uint16(handle))
}

//export Slice_uint16_elem
func Slice_uint16_elem(handle CGoHandle, _idx int) C.ushort {
	s := deptrFromHandle_Slice_uint16(handle)
	return C.ushort(s[_idx])
}

//export Slice_uint16_subslice
func Slice_uint16_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_uint16(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_uint16(&ss))
}

//export Slice_uint16_set
func Slice_uint16_set(handle CGoHandle, _idx int, _vl C.ushort) {
	s := deptrFromHandle_Slice_uint16(handle)
	s[_idx] = uint16(_vl)
}

//export Slice_uint16_append
func Slice_uint16_append(handle CGoHandle, _vl C.ushort) {
	s := ptrFromHandle_Slice_uint16(handle)
	*s = append(*s, uint16(_vl))
}

// Converters for implicit pointer handles for type: []uint32
func ptrFromHandle_Slice_uint32(h CGoHandle) *[]uint32 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]uint32")
	if p == nil {
		return nil
	}
	return p.(*[]uint32)
}
func deptrFromHandle_Slice_uint32(h CGoHandle) []uint32 {
	p := ptrFromHandle_Slice_uint32(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_uint32(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]uint32", p))
}

// --- wrapping slice: []uint32 ---
//export Slice_uint32_CTor
func Slice_uint32_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_uint32(&[]uint32{}))
}

//export Slice_uint32_len
func Slice_uint32_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_uint32(handle))
}

//export Slice_uint32_elem
func Slice_uint32_elem(handle CGoHandle, _idx int) C.ulong {
	s := deptrFromHandle_Slice_uint32(handle)
	return C.ulong(s[_idx])
}

//export Slice_uint32_subslice
func Slice_uint32_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_uint32(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_uint32(&ss))
}

//export Slice_uint32_set
func Slice_uint32_set(handle CGoHandle, _idx int, _vl C.ulong) {
	s := deptrFromHandle_Slice_uint32(handle)
	s[_idx] = uint32(_vl)
}

//export Slice_uint32_append
func Slice_uint32_append(handle CGoHandle, _vl C.ulong) {
	s := ptrFromHandle_Slice_uint32(handle)
	*s = append(*s, uint32(_vl))
}

// Converters for implicit pointer handles for type: []uint64
func ptrFromHandle_Slice_uint64(h CGoHandle) *[]uint64 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]uint64")
	if p == nil {
		return nil
	}
	return p.(*[]uint64)
}
func deptrFromHandle_Slice_uint64(h CGoHandle) []uint64 {
	p := ptrFromHandle_Slice_uint64(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_uint64(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]uint64", p))
}

// --- wrapping slice: []uint64 ---
//export Slice_uint64_CTor
func Slice_uint64_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_uint64(&[]uint64{}))
}

//export Slice_uint64_len
func Slice_uint64_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_uint64(handle))
}

//export Slice_uint64_elem
func Slice_uint64_elem(handle CGoHandle, _idx int) C.ulonglong {
	s := deptrFromHandle_Slice_uint64(handle)
	return C.ulonglong(s[_idx])
}

//export Slice_uint64_subslice
func Slice_uint64_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_uint64(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_uint64(&ss))
}

//export Slice_uint64_set
func Slice_uint64_set(handle CGoHandle, _idx int, _vl C.ulonglong) {
	s := deptrFromHandle_Slice_uint64(handle)
	s[_idx] = uint64(_vl)
}

//export Slice_uint64_append
func Slice_uint64_append(handle CGoHandle, _vl C.ulonglong) {
	s := ptrFromHandle_Slice_uint64(handle)
	*s = append(*s, uint64(_vl))
}

// Converters for implicit pointer handles for type: []uint8
func ptrFromHandle_Slice_uint8(h CGoHandle) *[]uint8 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]uint8")
	if p == nil {
		return nil
	}
	return p.(*[]uint8)
}
func deptrFromHandle_Slice_uint8(h CGoHandle) []uint8 {
	p := ptrFromHandle_Slice_uint8(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_uint8(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]uint8", p))
}

// --- wrapping slice: []uint8 ---
//export Slice_uint8_CTor
func Slice_uint8_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_uint8(&[]uint8{}))
}

//export Slice_uint8_len
func Slice_uint8_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_uint8(handle))
}

//export Slice_uint8_elem
func Slice_uint8_elem(handle CGoHandle, _idx int) C.uchar {
	s := deptrFromHandle_Slice_uint8(handle)
	return C.uchar(s[_idx])
}

//export Slice_uint8_subslice
func Slice_uint8_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_uint8(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_uint8(&ss))
}

//export Slice_uint8_set
func Slice_uint8_set(handle CGoHandle, _idx int, _vl C.uchar) {
	s := deptrFromHandle_Slice_uint8(handle)
	s[_idx] = uint8(_vl)
}

//export Slice_uint8_append
func Slice_uint8_append(handle CGoHandle, _vl C.uchar) {
	s := ptrFromHandle_Slice_uint8(handle)
	*s = append(*s, uint8(_vl))
}

// ---- Package: api ---

// ---- Types ---

// Converters for implicit pointer handles for type: []*interactions.AgentConfig
func ptrFromHandle_Slice_Ptr_interactions_AgentConfig(h CGoHandle) *[]*interactions.AgentConfig {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]*interactions.AgentConfig")
	if p == nil {
		return nil
	}
	return p.(*[]*interactions.AgentConfig)
}
func deptrFromHandle_Slice_Ptr_interactions_AgentConfig(h CGoHandle) []*interactions.AgentConfig {
	p := ptrFromHandle_Slice_Ptr_interactions_AgentConfig(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_Ptr_interactions_AgentConfig(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]*interactions.AgentConfig", p))
}

// --- wrapping slice: []*interactions.AgentConfig ---
//export Slice_Ptr_interactions_AgentConfig_CTor
func Slice_Ptr_interactions_AgentConfig_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_Ptr_interactions_AgentConfig(&[]*interactions.AgentConfig{}))
}

//export Slice_Ptr_interactions_AgentConfig_len
func Slice_Ptr_interactions_AgentConfig_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_Ptr_interactions_AgentConfig(handle))
}

//export Slice_Ptr_interactions_AgentConfig_elem
func Slice_Ptr_interactions_AgentConfig_elem(handle CGoHandle, _idx int) CGoHandle {
	s := deptrFromHandle_Slice_Ptr_interactions_AgentConfig(handle)
	return handleFromPtr_Ptr_interactions_AgentConfig(s[_idx])
}

//export Slice_Ptr_interactions_AgentConfig_subslice
func Slice_Ptr_interactions_AgentConfig_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_Ptr_interactions_AgentConfig(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_Ptr_interactions_AgentConfig(&ss))
}

//export Slice_Ptr_interactions_AgentConfig_set
func Slice_Ptr_interactions_AgentConfig_set(handle CGoHandle, _idx int, _vl CGoHandle) {
	s := deptrFromHandle_Slice_Ptr_interactions_AgentConfig(handle)
	s[_idx] = ptrFromHandle_Ptr_interactions_AgentConfig(_vl)
}

//export Slice_Ptr_interactions_AgentConfig_append
func Slice_Ptr_interactions_AgentConfig_append(handle CGoHandle, _vl CGoHandle) {
	s := ptrFromHandle_Slice_Ptr_interactions_AgentConfig(handle)
	*s = append(*s, ptrFromHandle_Ptr_interactions_AgentConfig(_vl))
}

// Converters for implicit pointer handles for type: []*simulator.OtherParams
func ptrFromHandle_Slice_Ptr_simulator_OtherParams(h CGoHandle) *[]*simulator.OtherParams {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]*simulator.OtherParams")
	if p == nil {
		return nil
	}
	return p.(*[]*simulator.OtherParams)
}
func deptrFromHandle_Slice_Ptr_simulator_OtherParams(h CGoHandle) []*simulator.OtherParams {
	p := ptrFromHandle_Slice_Ptr_simulator_OtherParams(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_Ptr_simulator_OtherParams(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]*simulator.OtherParams", p))
}

// --- wrapping slice: []*simulator.OtherParams ---
//export Slice_Ptr_simulator_OtherParams_CTor
func Slice_Ptr_simulator_OtherParams_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_Ptr_simulator_OtherParams(&[]*simulator.OtherParams{}))
}

//export Slice_Ptr_simulator_OtherParams_len
func Slice_Ptr_simulator_OtherParams_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_Ptr_simulator_OtherParams(handle))
}

//export Slice_Ptr_simulator_OtherParams_elem
func Slice_Ptr_simulator_OtherParams_elem(handle CGoHandle, _idx int) CGoHandle {
	s := deptrFromHandle_Slice_Ptr_simulator_OtherParams(handle)
	return handleFromPtr_Ptr_simulator_OtherParams(s[_idx])
}

//export Slice_Ptr_simulator_OtherParams_subslice
func Slice_Ptr_simulator_OtherParams_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_Ptr_simulator_OtherParams(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_Ptr_simulator_OtherParams(&ss))
}

//export Slice_Ptr_simulator_OtherParams_set
func Slice_Ptr_simulator_OtherParams_set(handle CGoHandle, _idx int, _vl CGoHandle) {
	s := deptrFromHandle_Slice_Ptr_simulator_OtherParams(handle)
	s[_idx] = ptrFromHandle_Ptr_simulator_OtherParams(_vl)
}

//export Slice_Ptr_simulator_OtherParams_append
func Slice_Ptr_simulator_OtherParams_append(handle CGoHandle, _vl CGoHandle) {
	s := ptrFromHandle_Slice_Ptr_simulator_OtherParams(handle)
	*s = append(*s, ptrFromHandle_Ptr_simulator_OtherParams(_vl))
}

// Converters for implicit pointer handles for type: [][]float64
func ptrFromHandle_Slice_Slice_float64(h CGoHandle) *[][]float64 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[][]float64")
	if p == nil {
		return nil
	}
	return p.(*[][]float64)
}
func deptrFromHandle_Slice_Slice_float64(h CGoHandle) [][]float64 {
	p := ptrFromHandle_Slice_Slice_float64(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_Slice_float64(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[][]float64", p))
}

// --- wrapping slice: [][]float64 ---
//export Slice_Slice_float64_CTor
func Slice_Slice_float64_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_Slice_float64(&[][]float64{}))
}

//export Slice_Slice_float64_len
func Slice_Slice_float64_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_Slice_float64(handle))
}

//export Slice_Slice_float64_elem
func Slice_Slice_float64_elem(handle CGoHandle, _idx int) CGoHandle {
	s := deptrFromHandle_Slice_Slice_float64(handle)
	return handleFromPtr_Slice_float64(s[_idx])
}

//export Slice_Slice_float64_subslice
func Slice_Slice_float64_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_Slice_float64(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_Slice_float64(&ss))
}

//export Slice_Slice_float64_set
func Slice_Slice_float64_set(handle CGoHandle, _idx int, _vl CGoHandle) {
	s := deptrFromHandle_Slice_Slice_float64(handle)
	s[_idx] = deptrFromHandle_Slice_float64(_vl)
}

//export Slice_Slice_float64_append
func Slice_Slice_float64_append(handle CGoHandle, _vl CGoHandle) {
	s := ptrFromHandle_Slice_Slice_float64(handle)
	*s = append(*s, deptrFromHandle_Slice_float64(_vl))
}

// Converters for implicit pointer handles for type: []simulator.Iteration
func ptrFromHandle_Slice_simulator_Iteration(h CGoHandle) *[]simulator.Iteration {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "[]simulator.Iteration")
	if p == nil {
		return nil
	}
	return p.(*[]simulator.Iteration)
}
func deptrFromHandle_Slice_simulator_Iteration(h CGoHandle) []simulator.Iteration {
	p := ptrFromHandle_Slice_simulator_Iteration(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Slice_simulator_Iteration(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("[]simulator.Iteration", p))
}

// --- wrapping slice: []simulator.Iteration ---
//export Slice_simulator_Iteration_CTor
func Slice_simulator_Iteration_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Slice_simulator_Iteration(&[]simulator.Iteration{}))
}

//export Slice_simulator_Iteration_len
func Slice_simulator_Iteration_len(handle CGoHandle) int {
	return len(deptrFromHandle_Slice_simulator_Iteration(handle))
}

//export Slice_simulator_Iteration_elem
func Slice_simulator_Iteration_elem(handle CGoHandle, _idx int) CGoHandle {
	s := deptrFromHandle_Slice_simulator_Iteration(handle)
	return handleFromPtr_simulator_Iteration(s[_idx])
}

//export Slice_simulator_Iteration_subslice
func Slice_simulator_Iteration_subslice(handle CGoHandle, _st, _ed int) CGoHandle {
	s := deptrFromHandle_Slice_simulator_Iteration(handle)
	ss := s[_st:_ed]
	return CGoHandle(handleFromPtr_Slice_simulator_Iteration(&ss))
}

//export Slice_simulator_Iteration_set
func Slice_simulator_Iteration_set(handle CGoHandle, _idx int, _vl CGoHandle) {
	s := deptrFromHandle_Slice_simulator_Iteration(handle)
	s[_idx] = ptrFromHandle_simulator_Iteration(_vl)
}

//export Slice_simulator_Iteration_append
func Slice_simulator_Iteration_append(handle CGoHandle, _vl CGoHandle) {
	s := ptrFromHandle_Slice_simulator_Iteration(handle)
	*s = append(*s, ptrFromHandle_simulator_Iteration(_vl))
}

// Converters for pointer handles for type: api.StepperOrRunner
func ptrFromHandle_api_StepperOrRunner(h CGoHandle) api.StepperOrRunner {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "api.StepperOrRunner")
	if p == nil {
		return nil
	}
	return p.(api.StepperOrRunner)
}
func handleFromPtr_api_StepperOrRunner(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("api.StepperOrRunner", p))
}

// Converters for implicit pointer handles for type: map[string][]bool
func ptrFromHandle_Map_string_Slice_bool(h CGoHandle) *map[string][]bool {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "map[string][]bool")
	if p == nil {
		return nil
	}
	return p.(*map[string][]bool)
}
func deptrFromHandle_Map_string_Slice_bool(h CGoHandle) map[string][]bool {
	p := ptrFromHandle_Map_string_Slice_bool(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Map_string_Slice_bool(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("map[string][]bool", p))
}

// --- wrapping map: map[string][]bool ---
//export Map_string_Slice_bool_CTor
func Map_string_Slice_bool_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Map_string_Slice_bool(&map[string][]bool{}))
}

//export Map_string_Slice_bool_len
func Map_string_Slice_bool_len(handle CGoHandle) int {
	return len(deptrFromHandle_Map_string_Slice_bool(handle))
}

//export Map_string_Slice_bool_elem
func Map_string_Slice_bool_elem(handle CGoHandle, _ky *C.char) CGoHandle {
	s := deptrFromHandle_Map_string_Slice_bool(handle)
	v, ok := s[C.GoString(_ky)]
	if !ok {
		C.PyErr_SetString(C.PyExc_KeyError, C.CString("key not in map"))
	}
	return handleFromPtr_Slice_bool(v)
}

//export Map_string_Slice_bool_contains
func Map_string_Slice_bool_contains(handle CGoHandle, _ky *C.char) C.char {
	s := deptrFromHandle_Map_string_Slice_bool(handle)
	_, ok := s[C.GoString(_ky)]
	return boolGoToPy(ok)
}

//export Map_string_Slice_bool_set
func Map_string_Slice_bool_set(handle CGoHandle, _ky *C.char, _vl CGoHandle) {
	s := deptrFromHandle_Map_string_Slice_bool(handle)
	s[C.GoString(_ky)] = deptrFromHandle_Slice_bool(_vl)
}

//export Map_string_Slice_bool_delete
func Map_string_Slice_bool_delete(handle CGoHandle, _ky *C.char) {
	s := deptrFromHandle_Map_string_Slice_bool(handle)
	delete(s, C.GoString(_ky))
}

//export Map_string_Slice_bool_keys
func Map_string_Slice_bool_keys(handle CGoHandle) CGoHandle {
	s := deptrFromHandle_Map_string_Slice_bool(handle)
	kys := make([]string, 0, len(s))
	for k := range s {
		kys = append(kys, k)
	}
	return handleFromPtr_Slice_string(&kys)
}

// Converters for implicit pointer handles for type: map[string][]float64
func ptrFromHandle_Map_string_Slice_float64(h CGoHandle) *map[string][]float64 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "map[string][]float64")
	if p == nil {
		return nil
	}
	return p.(*map[string][]float64)
}
func deptrFromHandle_Map_string_Slice_float64(h CGoHandle) map[string][]float64 {
	p := ptrFromHandle_Map_string_Slice_float64(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Map_string_Slice_float64(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("map[string][]float64", p))
}

// --- wrapping map: map[string][]float64 ---
//export Map_string_Slice_float64_CTor
func Map_string_Slice_float64_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Map_string_Slice_float64(&map[string][]float64{}))
}

//export Map_string_Slice_float64_len
func Map_string_Slice_float64_len(handle CGoHandle) int {
	return len(deptrFromHandle_Map_string_Slice_float64(handle))
}

//export Map_string_Slice_float64_elem
func Map_string_Slice_float64_elem(handle CGoHandle, _ky *C.char) CGoHandle {
	s := deptrFromHandle_Map_string_Slice_float64(handle)
	v, ok := s[C.GoString(_ky)]
	if !ok {
		C.PyErr_SetString(C.PyExc_KeyError, C.CString("key not in map"))
	}
	return handleFromPtr_Slice_float64(v)
}

//export Map_string_Slice_float64_contains
func Map_string_Slice_float64_contains(handle CGoHandle, _ky *C.char) C.char {
	s := deptrFromHandle_Map_string_Slice_float64(handle)
	_, ok := s[C.GoString(_ky)]
	return boolGoToPy(ok)
}

//export Map_string_Slice_float64_set
func Map_string_Slice_float64_set(handle CGoHandle, _ky *C.char, _vl CGoHandle) {
	s := deptrFromHandle_Map_string_Slice_float64(handle)
	s[C.GoString(_ky)] = deptrFromHandle_Slice_float64(_vl)
}

//export Map_string_Slice_float64_delete
func Map_string_Slice_float64_delete(handle CGoHandle, _ky *C.char) {
	s := deptrFromHandle_Map_string_Slice_float64(handle)
	delete(s, C.GoString(_ky))
}

//export Map_string_Slice_float64_keys
func Map_string_Slice_float64_keys(handle CGoHandle) CGoHandle {
	s := deptrFromHandle_Map_string_Slice_float64(handle)
	kys := make([]string, 0, len(s))
	for k := range s {
		kys = append(kys, k)
	}
	return handleFromPtr_Slice_string(&kys)
}

// Converters for implicit pointer handles for type: map[string][]int64
func ptrFromHandle_Map_string_Slice_int64(h CGoHandle) *map[string][]int64 {
	p := gopyh.VarFromHandle((gopyh.CGoHandle)(h), "map[string][]int64")
	if p == nil {
		return nil
	}
	return p.(*map[string][]int64)
}
func deptrFromHandle_Map_string_Slice_int64(h CGoHandle) map[string][]int64 {
	p := ptrFromHandle_Map_string_Slice_int64(h)
	if p == nil {
		return nil
	}
	return *p
}
func handleFromPtr_Map_string_Slice_int64(p interface{}) CGoHandle {
	return CGoHandle(gopyh.Register("map[string][]int64", p))
}

// --- wrapping map: map[string][]int64 ---
//export Map_string_Slice_int64_CTor
func Map_string_Slice_int64_CTor() CGoHandle {
	return CGoHandle(handleFromPtr_Map_string_Slice_int64(&map[string][]int64{}))
}

//export Map_string_Slice_int64_len
func Map_string_Slice_int64_len(handle CGoHandle) int {
	return len(deptrFromHandle_Map_string_Slice_int64(handle))
}

//export Map_string_Slice_int64_elem
func Map_string_Slice_int64_elem(handle CGoHandle, _ky *C.char) CGoHandle {
	s := deptrFromHandle_Map_string_Slice_int64(handle)
	v, ok := s[C.GoString(_ky)]
	if !ok {
		C.PyErr_SetString(C.PyExc_KeyError, C.CString("key not in map"))
	}
	return handleFromPtr_Slice_int64(v)
}

//export Map_string_Slice_int64_contains
func Map_string_Slice_int64_contains(handle CGoHandle, _ky *C.char) C.char {
	s := deptrFromHandle_Map_string_Slice_int64(handle)
	_, ok := s[C.GoString(_ky)]
	return boolGoToPy(ok)
}

//export Map_string_Slice_int64_set
func Map_string_Slice_int64_set(handle CGoHandle, _ky *C.char, _vl CGoHandle) {
	s := deptrFromHandle_Map_string_Slice_int64(handle)
	s[C.GoString(_ky)] = deptrFromHandle_Slice_int64(_vl)
}

//export Map_string_Slice_int64_delete
func Map_string_Slice_int64_delete(handle CGoHandle, _ky *C.char) {
	s := deptrFromHandle_Map_string_Slice_int64(handle)
	delete(s, C.GoString(_ky))
}

//export Map_string_Slice_int64_keys
func Map_string_Slice_int64_keys(handle CGoHandle) CGoHandle {
	s := deptrFromHandle_Map_string_Slice_int64(handle)
	kys := make([]string, 0, len(s))
	for k := range s {
		kys = append(kys, k)
	}
	return handleFromPtr_Slice_string(&kys)
}

// ---- Global Variables: can only use functions to access ---

// ---- Interfaces ---

//export api_StepperOrRunner_ReadyToTerminate
func api_StepperOrRunner_ReadyToTerminate(_handle CGoHandle) C.char {
	_saved_thread := C.PyEval_SaveThread()
	defer C.PyEval_RestoreThread(_saved_thread)
	vifc, __err := gopyh.VarFromHandleTry((gopyh.CGoHandle)(_handle), "api.StepperOrRunner")
	if __err != nil {
		return boolGoToPy(false)
	}
	return boolGoToPy(vifc.(api.StepperOrRunner).ReadyToTerminate())

}

//export api_StepperOrRunner_Run
func api_StepperOrRunner_Run(_handle CGoHandle, goRun C.char) {
	_saved_thread := C.PyEval_SaveThread()
	defer C.PyEval_RestoreThread(_saved_thread)
	vifc, __err := gopyh.VarFromHandleTry((gopyh.CGoHandle)(_handle), "api.StepperOrRunner")
	if __err != nil {
		return
	}
	if boolPyToGo(goRun) {
		go vifc.(api.StepperOrRunner).Run()
	} else {
		vifc.(api.StepperOrRunner).Run()
	}
}

//export api_StepperOrRunner_Step
func api_StepperOrRunner_Step(_handle CGoHandle, wg CGoHandle, goRun C.char) {
	_saved_thread := C.PyEval_SaveThread()
	defer C.PyEval_RestoreThread(_saved_thread)
	vifc, __err := gopyh.VarFromHandleTry((gopyh.CGoHandle)(_handle), "api.StepperOrRunner")
	if __err != nil {
		return
	}
	if boolPyToGo(goRun) {
		go vifc.(api.StepperOrRunner).Step(ptrFromHandle_Ptr_sync_WaitGroup(wg))
	} else {
		vifc.(api.StepperOrRunner).Step(ptrFromHandle_Ptr_sync_WaitGroup(wg))
	}
}

// ---- Structs ---

// ---- Slices ---

// ---- Maps ---

// ---- Constructors ---

// ---- Functions ---

//export api_RunSimulator
func api_RunSimulator(goRun C.char) {
	_saved_thread := C.PyEval_SaveThread()
	defer C.PyEval_RestoreThread(_saved_thread)
	if boolPyToGo(goRun) {
		go api.RunSimulator()
	} else {
		api.RunSimulator()
	}
}

//export api_LoadStepperOrRunner
func api_LoadStepperOrRunner(settings CGoHandle, implementations CGoHandle, agents CGoHandle) CGoHandle {
	_saved_thread := C.PyEval_SaveThread()
	defer C.PyEval_RestoreThread(_saved_thread)
	return handleFromPtr_api_StepperOrRunner(api.LoadStepperOrRunner(ptrFromHandle_Ptr_simulator_LoadSettingsConfig(settings), ptrFromHandle_Ptr_simulator_LoadImplementationsConfig(implementations), deptrFromHandle_Slice_Ptr_interactions_AgentConfig(agents)))

}
