other_params:
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    transitions_from_0: [1, 2, 3]
    transitions_from_1: [0, 3]
    transitions_from_2: [1]
    transitions_from_3: [0]
    transition_rates_partition_index: [0]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    transitions_from_0: [1, 2, 3]
    transitions_from_1: [0, 3]
    transitions_from_2: [1]
    transitions_from_3: [0]
    transition_rates_partition_index: [2]
- float_params: {}
  int_params:
    connected_partitions: [1, 3]
    connected_value_indices: [0]
init_state_values:
- [1.0, 2.0, 1.0, 1.0, 0.3, 1.2, 0.1, 1.0]
- [0]
- [1.0, 2.0, 1.0, 1.0, 0.3, 1.2, 0.1, 1.0]
- [0]
- [0, 0, 0, 0]
seeds: [0, 11112222, 0, 2525221, 0]
state_widths: [8, 1, 8, 1, 4]
state_history_depths: [2, 2, 2, 2, 2]
timesteps_history_depth: 2