other_params:
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: []
    incoming_partition_state_values: []
    incoming_object_state_values: []
    downstream_partitions: [5]
    downstream_flow_rates_partition_index: [0]
    object_dispatch_probs_partition_index: [1]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: [2]
    incoming_partition_state_values: [6]
    incoming_object_state_values: [5]
    downstream_partitions: [8, 11]
    downstream_flow_rates_partition_index: [3]
    object_dispatch_probs_partition_index: [4]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: [5]
    incoming_partition_state_values: [6]
    incoming_object_state_values: [5]
    downstream_partitions: [11]
    downstream_flow_rates_partition_index: [6]
    object_dispatch_probs_partition_index: [7]
- float_params: {}
  int_params: {}
- float_params: {}
  int_params: {}
- float_params: {}
  int_params:
    upstream_partitions: [5, 8]
    incoming_partition_state_values: [6, 6]
    incoming_object_state_values: [5, 5]
    downstream_partitions: [-1]
    downstream_flow_rates_partition_index: [9]
    object_dispatch_probs_partition_index: [10]
init_state_values:
- [1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [1e8, 1e8, 1e8, 1e8, 1e8, -1, -1]
- [1.0, 1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [0, 0, 0, 0, 0, -1, -1]
- [1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [0, 0, 0, 0, 0, -1, -1]
- [1.0]
- [0.2, 0.2, 0.2, 0.2, 0.2]
- [0, 0, 0, 0, 0, -1, -1]
seeds: [0, 0, 123563, 0, 0, 352, 0, 0, 11231, 0, 0, 7641]
state_widths: [1, 5, 7, 2, 5, 7, 1, 5, 7, 1, 5, 7]
state_history_depths: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
timesteps_history_depth: 2